name: Lint, Build, Test, Deploy - Multi-job Workflow
on:
    push:
        branches:
            - practice01
    workflow_dispatch:
jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Output Commands
              run: |
                  pwd
                  dir
                  ls
            - name: Install Dependencies
              run: npm ci
    lint:
        runs-on: ubuntu-latest
        needs: checkout
        steps:
            - name: Run Lint
              run: npm run lint
    test:
        runs-on: ubuntu-latest
        needs: checkout
        steps:
            - name: Run Unit Tests
              run: npm run test
    build:
        runs-on: ubuntu-latest
        needs: checkout
        steps:
            - name: Build
              run: npm run build
    deploy:
        runs-on: ubuntu-latest
        needs: [lint, test, build]
        steps:
            - name: Deploy
              run: echo Deploying...
