name: Lint, Build, Test, Deploy - Single Job Workflow
on:
    push:
        branches:
            - practice01
    workflow_dispatch:
jobs:
    lint-test-build-deploy-single-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Run Commands
              run: |
                  pwd
                  dir
                  echo hey
                  ls
            - name: Install Dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Test
              run: npm run test
            - name: Build
              run: npm run build
            - name: Deploy
              run: echo Deploying...
